### PR TITLE
2.2.0-beta.17

### PR DESCRIPTION
**Pull request by thieren**
### Changed

- eufy-security-client library is now added as forked dependency to enable direct changes

### Fixed

- Trying to fix login issue #250
- Fixed installation issues with previous betas
- Package size was dramatically reduced by removing cache files

### CODE REVIEW

**Comment by PeterAlexander75** [comment]
Just got beta 15 working - not sure if I'm brave enough to try upgrading to 17...

**Comment by thieren** [comment]
> Just got beta 15 working - not sure if I'm brave enough to try upgrading to 17...

I think the install should be fine now. But you could also wait for other users to report back. ;-)

**Comment by adekka** [comment]
I still got the same error after installing this beta: 
[12/23/2022, 1:24:09 PM] [EufySecurity-2.2.0-beta.17] ERROR: Not connected can't continue!

I haven't changed the username or password.

**Comment by thieren** [comment]
@adekka 

Please login again with the config-ui. This will reset the persistent data from previous logins.

If this does not work I'd like you to try a new guest account if possible.

Is there a captcha warning before the 'can't continue' message?

**Comment by PeterAlexander75** [comment]
> I still got the same error after installing this beta: [12/23/2022, 1:24:09 PM] [EufySecurity-2.2.0-beta.17] ERROR: Not connected can't continue!
> 
> I haven't changed the username or password.

Try logging out or back in again. Even better, use a different account.

**Comment by adekka** [comment]
logging in with the same account gave me the same error. I created a new account and now I get the 'captch' warning.

**Comment by thieren** [comment]
> logging in with the same account gave me the same error. I created a new account and now I get the 'captcha' warning.

Did you login via config-ui? Or just changed the credentials in the json?

**Comment by adekka** [comment]
I logged in via config-ui

**Comment by adekka** [comment]
and after a restart I got stuck with the 'captcha' error again. Let me know if I can help in any way

**Pull request merged**
