### PR TITLE
add support for solocam S220

### PR DESCRIPTION
**Pull request by ubreu**

### CODE REVIEW

**Comment by JayShallcrass** [comment]
@ubreu thanks for adding S220 support, definitely needed!
I've installed in homebridge but doesn't look like the config UI is working, do I need to do it in the JSON instead? cheers

**Comment by ubreu** [comment]
@JayShallcrass : I will check to see whether the config editor loads for me and will get back to you.

**Comment by lenoxys** [comment]
hello, thanks for your contribution. I would suggest to work with the HKSV branch instead of the master one. I've done a lot of modification on HKSV branch including getting ride of static linking to device type and relying more on the capacity of the device such as `IsCamera()` or `isLock()`

**Comment by ubreu** [comment]
@lenoxys : Ok, I will try that next

**Pull request closed without merging**
